// Generated by CoffeeScript 1.4.0
(function() {

  window.ProblemsCtrl = function($scope, $http) {
    var promise;
    $scope.problems = [];
    promise = $http({
      method: "GET",
      url: "http://localhost:3000/problems"
    });
    promise.success(function(res) {
      return $scope.problems = res;
    });
    return promise.error(function(res) {
      return console.log("Error: ", res);
    });
  };

  window.ProblemCtrl = function($scope, $http) {
    var $id;
    $id = $scope.id;
    $scope.problem = "";
    $scope.solved = false;
    $scope.show = false;
    $scope.toggleShow = function() {
      var promise;
      $scope.show = !$scope.show;
      if ($scope.show && !$scope.problem) {
        promise = $http({
          method: "GET",
          url: "http://localhost:3000/problem/" + $id
        });
        promise.success(function(res) {
          return $scope.problem = res;
        });
        return promise.error(function(res) {
          return console.log("Error: ", res);
        });
      }
    };
    if ($id === "DeMorgan") {
      $scope.toggleShow();
    }
    $scope.result = "";
    return $scope.submit = function() {
      var submit_promise;
      $scope.result = "Submitted!";
      submit_promise = $http({
        method: "POST",
        url: "http://localhost:3000/solve/" + $id,
        data: $scope.problem
      });
      submit_promise.success(function(res) {
        $scope.result = res.stdout.replace(RegExp("/home/dan/code/agder/solutions/" + $id + "/[^/]*/([^\\.]*).agda", "g"), function(filename, short) {
          return short + ".agda";
        });
        if (res.exitcode === 0) {
          return $scope.solved = true;
        }
      });
      return submit_promise.error(function(res) {
        return $scope.result = res;
      });
    };
  };

}).call(this);
