// Generated by CoffeeScript 1.4.0
(function() {

  window.agder_module = angular.module('agder', []);

  agder_module.factory('make_url', function() {
    return function(s) {
      return ("http://" + window.location.host) + s;
    };
  });

}).call(this);
