// Generated by CoffeeScript 1.4.0
(function() {
  var make_url;

  make_url = function(s) {
    return ("http://" + window.location.host) + s;
  };

  window.ProblemsCtrl = function($scope, $http) {
    var promise;
    $scope.problems = [];
    promise = $http({
      method: "GET",
      url: make_url("/problems")
    });
    promise.success(function(res) {
      return $scope.problems = res;
    });
    return promise.error(function(res) {
      return console.log("Error: ", res);
    });
  };

  window.ProblemCtrl = function($scope, $http, $location) {
    var $id;
    $id = $scope.id;
    $scope.problem = "";
    $scope.solved = false;
    $scope.toggleShow = function() {
      $scope.show = !$scope.show;
      return $scope.updateShow();
    };
    $scope.updateShow = function() {
      var promise;
      if ($scope.show && !$scope.problem) {
        promise = $http({
          method: "GET",
          url: make_url("/problem/" + $id)
        });
        promise.success(function(res) {
          return $scope.problem = res;
        });
        return promise.error(function(res) {
          return console.log("Error: ", res);
        });
      }
    };
    $scope.loc = $location;
    $scope.$watch('loc.search()', function() {
      $scope.show = $location.search()[$id] != null;
      return $scope.updateShow();
    });
    $scope.$watch('show', function() {
      return $location.search($id, $scope.show || null);
    });
    $scope.result = "";
    return $scope.submit = function() {
      var submit_promise;
      $scope.result = "Submitted!";
      submit_promise = $http({
        method: "POST",
        url: make_url("/solve/" + $id),
        data: $scope.problem
      });
      submit_promise.success(function(res) {
        $scope.result = res.stdout.replace(RegExp("/home/dan/code/agder/solutions/" + $id + "/[^/]*/([^\\.]*).agda", "g"), function(filename, short) {
          return short + ".agda";
        });
        if (res.exitcode === 0) {
          return $scope.solved = true;
        }
      });
      return submit_promise.error(function(res) {
        return $scope.result = res;
      });
    };
  };

}).call(this);
