// Generated by CoffeeScript 1.4.0
(function() {

  agder_module.factory('credentials', function($http, make_url) {
    var credentials, get_salt, hash, login, logout, parse_status, password, register, salt, status, update_credentials, username;
    hash = function() {
      return CryptoJS.SHA256(salt + password).toString(CryptoJS.enc.Hex);
    };
    update_credentials = function() {
      if (status === "CredentialsOK") {
        return {
          Credentials: {
            cred_user: username,
            cred_hash: hash()
          }
        };
      } else {
        return {
          Anonymous: []
        };
      }
    };
    username = "";
    password = "";
    salt = "";
    status = "NotLoggedIn";
    credentials = update_credentials();
    logout = function(cb) {
      username = "";
      password = "";
      salt = "";
      status = "NotLoggedIn";
      credentials = update_credentials();
      return cb();
    };
    logout(function() {});
    parse_status = function(res) {
      var key;
      for (key in res) {
        return key;
      }
      return "NotLoggedIn";
    };
    get_salt = function(cont) {
      return $http.post(make_url("/salt"), {
        d: username
      }).error(console.log).success(function(res) {
        salt = res;
        status = "SaltReceived";
        return cont();
      });
    };
    register = function(cb, _username, _password) {
      username = _username;
      password = _password;
      return get_salt(function() {
        return $http.post(make_url("/register"), {
          Credentials: {
            cred_user: username,
            cred_hash: hash()
          }
        }).success(function(res) {
          status = parse_status(res);
          cb();
          if (status === "SuccessfulCreation") {
            return login(cb, _username, _password);
          }
        });
      });
    };
    login = function(cb, _username, _password) {
      username = _username;
      password = _password;
      return get_salt(function() {
        return $http.post(make_url("/login"), {
          Credentials: {
            cred_user: username,
            cred_hash: hash()
          }
        }).success(function(res) {
          status = parse_status(res);
          update_credentials();
          return cb();
        });
      });
    };
    return {
      get: function() {
        return credentials;
      },
      parse_status: parse_status,
      status: function() {
        return status;
      },
      register: register,
      login: login,
      logout: logout
    };
  });

}).call(this);
