// Generated by CoffeeScript 1.4.0
(function() {

  agder_module.factory('credentials', function($http, make_url, $rootScope) {
    var get_salt, hash, login, logout, parse_status, register, update_credentials;
    hash = function(salt, password) {
      return CryptoJS.SHA256(salt + password).toString(CryptoJS.enc.Hex);
    };
    update_credentials = function(status, username, h) {
      $rootScope.status = status;
      return $rootScope.credentials = $rootScope.status === "CredentialsOK" ? {
        Credentials: {
          cred_user: username,
          cred_hash: h
        }
      } : {
        Anonymous: []
      };
    };
    logout = function() {
      return update_credentials("NotLoggedIn");
    };
    logout();
    parse_status = function(res) {
      var key;
      for (key in res) {
        return key;
      }
      return "NotLoggedIn";
    };
    get_salt = function(username, cont) {
      return $http.post(make_url("/salt"), {
        d: username
      }).error(console.log).success(cont);
    };
    register = function(username, password) {
      return get_salt(username, function(salt) {
        return $http.post(make_url("/register"), {
          Credentials: {
            cred_user: username,
            cred_hash: hash(salt, password)
          }
        }).success(function(res) {
          $rootScope.status = parse_status(res);
          if ($rootScope.status === "SuccessfulCreation") {
            return login(username, password);
          }
        });
      });
    };
    login = function(username, password) {
      return get_salt(username, function(salt) {
        var h;
        h = hash(salt, password);
        return $http.post(make_url("/login"), {
          Credentials: {
            cred_user: username,
            cred_hash: h
          }
        }).success(function(res) {
          return update_credentials(parse_status(res), username, h);
        });
      });
    };
    return {
      register: register,
      login: login,
      logout: logout
    };
  });

}).call(this);
