// Generated by CoffeeScript 1.4.0
(function() {

  agder_module.controller('LoginCtrl', function($scope, $rootScope, credentials) {
    $scope.username = "";
    $scope.password = "";
    $scope.logged_in = function() {
      return $rootScope.status === "CredentialsOK";
    };
    $scope.execute = function(fn) {
      return function() {
        return fn($scope.username, $scope.password);
      };
    };
    $scope.register = $scope.execute(credentials.register);
    $scope.login = $scope.execute(credentials.login);
    return $scope.logout = function() {
      $scope.username = "";
      $scope.password = "";
      return $scope.execute(credentials.logout)();
    };
  });

}).call(this);
