// Generated by CoffeeScript 1.4.0
(function() {

  agder_module.directive('markdown', function() {
    var converter, link;
    converter = new Showdown.converter();
    link = function(scope, element, attrs, model) {
      var render;
      render = function() {
        var htmlText;
        if (model.$modelValue) {
          htmlText = converter.makeHtml(model.$modelValue);
        } else {
          htmlText = "";
        }
        return element.html(htmlText);
      };
      scope.$watch(attrs['ngModel'], render);
      return render();
    };
    return {
      restrict: 'E',
      require: 'ngModel',
      link: link
    };
  });

}).call(this);
