// Generated by CoffeeScript 1.4.0
(function() {

  agder_module.controller('ProblemsCtrl', function($scope, $http, make_url) {
    $scope.problems = [];
    return $http.get(make_url("/problems")).error(console.log).success(function(res) {
      return $scope.problems = res;
    });
  }).controller('ProblemCtrl', function($scope, $http, $location, credentials, make_url) {
    var $id;
    $id = $scope.id;
    angular.extend($scope, {
      problem: "",
      definitions: "",
      description: "",
      result: "",
      solved: false
    });
    $scope.loc = $location;
    $scope.$watch('loc.search()', function() {
      $scope.show = $location.search()[$id] != null;
      return $scope.updateShow();
    });
    $scope.$watch('show', function() {
      return $location.search($id, $scope.show || null);
    });
    $scope.toggleShow = function() {
      $scope.show = !$scope.show;
      return $scope.updateShow();
    };
    $scope.updateShow = function() {
      if ($scope.show && !$scope.problem) {
        return $http.get(make_url("/problem/" + $id)).error(console.log).success(function(res) {
          return angular.extend($scope, {
            problem: res.problem,
            definitions: res.definitions || "",
            description: res.description || ""
          });
        });
      }
    };
    return $scope.submit = function() {
      $scope.result = "Submitted!";
      return $http.post(make_url("/solve/" + $id), {
        credentials: credentials.get(),
        solution: $scope.problem
      }).error(console.log).success(function(res) {
        var status;
        status = credentials.parse_status(res.user_status);
        if (status === "CredentialsOK") {
          $scope.result = res.stdout.replace(RegExp("/home/dan/code/agder/solutions/" + $id + "/[^/]*/([^\\.]*).agda", "g"), function(filename, short) {
            return short + ".agda";
          });
          if (res.exitcode === 0) {
            return $scope.solved = true;
          }
        } else {
          return $scope.result = status;
        }
      });
    };
  });

}).call(this);
